apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger-service
  template:
    metadata:
      labels:
        app: logger-service
    spec:
      containers:
        - name: logger-service
          image: boradocker26/master-work-logger-serivice:1.0.0
          env:
            - name: MONGO_DATABASE_URL
              value: "mongodb://host.minikube.internal:27017/master_work"
            - name: GRPC_SERVER_HOST
              value: ":5001"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          ports:
            - containerPort: 5001


---


apiVersion: v1
kind: Service
metadata:
  name: logger-service
spec:
  selector:
    app: logger-service
  ports:
    - protocol: TCP
      name: grpc-port
      port: 5001
      targetPort: 5001

