apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-generator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-generator-service
  template:
    metadata:
      labels:
        app: pdf-generator-service
    spec:
      containers:
        - name: pdf-generator-service
          image: boradocker26/master-work-pdf-generator-serivice:1.0.0
          env:
            - name: GRPC_SERVER_HOST
              value: ":5003"
            - name: HTTP_SERVER_HOST
              value: ":4003"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          ports:
            - containerPort: 4003
            - containerPort: 5003


---


apiVersion: v1
kind: Service
metadata:
  name: pdf-generator-service
spec:
  selector:
    app: pdf-generator-service
  ports:
    - protocol: TCP
      name: web-port
      port: 4003
      targetPort: 4003
    - protocol: TCP
      name: grpc-port
      port: 5003
      targetPort: 5003

